import {
  Lead,
  Deal,
  ActivityWithAuthor,
  LeadWithCounts,
  DealWithLead,
} from "@/types/database";

// ---------- MEMBERS (simplified for mock) ----------

export const MOCK_MEMBERS = [
  { id: "user-1", name: "Ana Silva", email: "ana@pipeflow.com" },
  { id: "user-2", name: "Carlos Souza", email: "carlos@pipeflow.com" },
  { id: "user-3", name: "Maria Santos", email: "maria@pipeflow.com" },
];

// ---------- LEADS ----------

export const MOCK_LEADS: LeadWithCounts[] = [
  {
    id: "lead-1",
    workspace_id: "ws-1",
    name: "João Mendes",
    email: "joao@techcorp.com",
    phone: "(11) 99999-1234",
    company: "TechCorp",
    position: "CTO",
    source: "Website",
    status: "qualified",
    assigned_to: "user-1",
    notes: "Interessado na solução enterprise. Já usa ferramenta concorrente.",
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-10T14:00:00Z",
    deals_count: 2,
    activities_count: 5,
    total_deal_value: 75000,
  },
  {
    id: "lead-2",
    workspace_id: "ws-1",
    name: "Fernanda Lima",
    email: "fernanda@startupx.io",
    phone: "(21) 98888-5678",
    company: "StartupX",
    position: "CEO",
    source: "Indicação",
    status: "new",
    assigned_to: "user-2",
    notes: "Startup em fase de crescimento. Budget limitado.",
    created_at: "2026-03-05T09:00:00Z",
    updated_at: "2026-03-05T09:00:00Z",
    deals_count: 1,
    activities_count: 2,
    total_deal_value: 12000,
  },
  {
    id: "lead-3",
    workspace_id: "ws-1",
    name: "Ricardo Alves",
    email: "ricardo@megaind.com.br",
    phone: "(31) 97777-9012",
    company: "Mega Indústria",
    position: "Diretor Comercial",
    source: "LinkedIn",
    status: "qualified",
    assigned_to: "user-1",
    notes: "Empresa grande, processo de decisão longo. Precisa de aprovação do board.",
    created_at: "2026-02-20T14:30:00Z",
    updated_at: "2026-03-08T11:00:00Z",
    deals_count: 1,
    activities_count: 8,
    total_deal_value: 150000,
  },
  {
    id: "lead-4",
    workspace_id: "ws-1",
    name: "Patrícia Costa",
    email: "patricia@designco.com",
    phone: "(41) 96666-3456",
    company: "DesignCo",
    position: "Head de Produto",
    source: "Evento",
    status: "new",
    assigned_to: "user-3",
    notes: null,
    created_at: "2026-03-10T16:00:00Z",
    updated_at: "2026-03-10T16:00:00Z",
    deals_count: 0,
    activities_count: 1,
    total_deal_value: 0,
  },
  {
    id: "lead-5",
    workspace_id: "ws-1",
    name: "Bruno Ferreira",
    email: "bruno@logistica360.com",
    phone: "(51) 95555-7890",
    company: "Logística 360",
    position: "Gerente de TI",
    source: "Google Ads",
    status: "disqualified",
    assigned_to: "user-2",
    notes: "Sem budget para este ano. Retomar contato em 2027.",
    created_at: "2026-02-15T08:00:00Z",
    updated_at: "2026-03-02T10:00:00Z",
    deals_count: 1,
    activities_count: 4,
    total_deal_value: 0,
  },
  {
    id: "lead-6",
    workspace_id: "ws-1",
    name: "Camila Rocha",
    email: "camila@educaplus.com",
    phone: "(61) 94444-2345",
    company: "EducaPlus",
    position: "Diretora",
    source: "Website",
    status: "qualified",
    assigned_to: "user-3",
    notes: "Interessada em plano pro. Quer demo para a equipe.",
    created_at: "2026-02-28T11:00:00Z",
    updated_at: "2026-03-09T15:00:00Z",
    deals_count: 1,
    activities_count: 6,
    total_deal_value: 36000,
  },
  {
    id: "lead-7",
    workspace_id: "ws-1",
    name: "Diego Martins",
    email: "diego@fastfood.com.br",
    phone: "(71) 93333-6789",
    company: "FastFood BR",
    position: "Sócio",
    source: "Indicação",
    status: "new",
    assigned_to: "user-1",
    notes: "Cadeia de restaurantes com 15 unidades.",
    created_at: "2026-03-11T13:00:00Z",
    updated_at: "2026-03-11T13:00:00Z",
    deals_count: 0,
    activities_count: 0,
    total_deal_value: 0,
  },
  {
    id: "lead-8",
    workspace_id: "ws-1",
    name: "Luciana Borges",
    email: "luciana@saude.med.br",
    phone: "(81) 92222-0123",
    company: "SaúdeMed",
    position: "Administradora",
    source: "LinkedIn",
    status: "new",
    assigned_to: "user-2",
    notes: "Clínica médica, 50 funcionários.",
    created_at: "2026-03-12T10:00:00Z",
    updated_at: "2026-03-12T10:00:00Z",
    deals_count: 0,
    activities_count: 1,
    total_deal_value: 0,
  },
];

// ---------- DEALS ----------

export const MOCK_DEALS: DealWithLead[] = [
  {
    id: "deal-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    title: "Licença Enterprise TechCorp",
    value: 50000,
    stage: "proposal_sent",
    assigned_to: "user-1",
    expected_close_date: "2026-04-15T00:00:00Z",
    closed_at: null,
    position: 0,
    created_at: "2026-03-02T10:00:00Z",
    updated_at: "2026-03-08T14:00:00Z",
    lead: { id: "lead-1", name: "João Mendes", company: "TechCorp" },
  },
  {
    id: "deal-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    title: "Módulo Analytics TechCorp",
    value: 25000,
    stage: "negotiation",
    assigned_to: "user-1",
    expected_close_date: "2026-04-30T00:00:00Z",
    closed_at: null,
    position: 0,
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-03-10T14:00:00Z",
    lead: { id: "lead-1", name: "João Mendes", company: "TechCorp" },
  },
  {
    id: "deal-3",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    title: "Plano Pro StartupX",
    value: 12000,
    stage: "contacted",
    assigned_to: "user-2",
    expected_close_date: "2026-05-01T00:00:00Z",
    closed_at: null,
    position: 0,
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-03-05T10:00:00Z",
    lead: { id: "lead-2", name: "Fernanda Lima", company: "StartupX" },
  },
  {
    id: "deal-4",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    title: "Contrato Anual Mega Indústria",
    value: 150000,
    stage: "proposal_sent",
    assigned_to: "user-1",
    expected_close_date: "2026-05-15T00:00:00Z",
    closed_at: null,
    position: 1,
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
    lead: { id: "lead-3", name: "Ricardo Alves", company: "Mega Indústria" },
  },
  {
    id: "deal-5",
    workspace_id: "ws-1",
    lead_id: "lead-6",
    title: "Plataforma EducaPlus",
    value: 36000,
    stage: "new_lead",
    assigned_to: "user-3",
    expected_close_date: "2026-06-01T00:00:00Z",
    closed_at: null,
    position: 0,
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-09T15:00:00Z",
    lead: { id: "lead-6", name: "Camila Rocha", company: "EducaPlus" },
  },
];

// ---------- ACTIVITIES ----------

export const MOCK_ACTIVITIES: ActivityWithAuthor[] = [
  {
    id: "act-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    deal_id: "deal-1",
    type: "meeting",
    description: "Reunião de apresentação do produto. Cliente demonstrou interesse na versão enterprise.",
    performed_by: "user-1",
    performed_at: "2026-03-10T14:00:00Z",
    created_at: "2026-03-10T14:30:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    deal_id: "deal-1",
    type: "email",
    description: "Enviada proposta comercial com valores e condições de pagamento.",
    performed_by: "user-1",
    performed_at: "2026-03-08T10:00:00Z",
    created_at: "2026-03-08T10:00:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-3",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    deal_id: null,
    type: "call",
    description: "Primeiro contato telefônico. Lead recebido via website.",
    performed_by: "user-1",
    performed_at: "2026-03-02T11:00:00Z",
    created_at: "2026-03-02T11:00:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-4",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    deal_id: "deal-2",
    type: "note",
    description: "Cliente solicitou módulo de analytics separado. Criar deal específico.",
    performed_by: "user-1",
    performed_at: "2026-03-05T16:00:00Z",
    created_at: "2026-03-05T16:00:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-5",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    deal_id: "deal-2",
    type: "meeting",
    description: "Demo do módulo analytics. Equipe técnica do cliente participou.",
    performed_by: "user-1",
    performed_at: "2026-03-10T10:00:00Z",
    created_at: "2026-03-10T10:30:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-6",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    deal_id: "deal-3",
    type: "call",
    description: "Contato inicial com a CEO. Startup em fase de crescimento rápido.",
    performed_by: "user-2",
    performed_at: "2026-03-05T15:00:00Z",
    created_at: "2026-03-05T15:00:00Z",
    author_name: "Carlos Souza",
    author_email: "carlos@pipeflow.com",
  },
  {
    id: "act-7",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    deal_id: null,
    type: "email",
    description: "Enviado material institucional e cases de sucesso.",
    performed_by: "user-2",
    performed_at: "2026-03-06T09:00:00Z",
    created_at: "2026-03-06T09:00:00Z",
    author_name: "Carlos Souza",
    author_email: "carlos@pipeflow.com",
  },
  {
    id: "act-8",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    deal_id: "deal-4",
    type: "meeting",
    description: "Reunião com diretor comercial e equipe de compras. Processo longo.",
    performed_by: "user-1",
    performed_at: "2026-03-08T11:00:00Z",
    created_at: "2026-03-08T11:30:00Z",
    author_name: "Ana Silva",
    author_email: "ana@pipeflow.com",
  },
  {
    id: "act-9",
    workspace_id: "ws-1",
    lead_id: "lead-4",
    deal_id: null,
    type: "call",
    description: "Primeiro contato após evento. Muito interessada no produto.",
    performed_by: "user-3",
    performed_at: "2026-03-10T17:00:00Z",
    created_at: "2026-03-10T17:00:00Z",
    author_name: "Maria Santos",
    author_email: "maria@pipeflow.com",
  },
  {
    id: "act-10",
    workspace_id: "ws-1",
    lead_id: "lead-8",
    deal_id: null,
    type: "email",
    description: "Lead entrou pelo LinkedIn. Enviado e-mail de boas-vindas.",
    performed_by: "user-2",
    performed_at: "2026-03-12T10:30:00Z",
    created_at: "2026-03-12T10:30:00Z",
    author_name: "Carlos Souza",
    author_email: "carlos@pipeflow.com",
  },
];

// ---------- HELPER FUNCTIONS ----------

export function getLeadById(id: string): LeadWithCounts | undefined {
  return MOCK_LEADS.find((l) => l.id === id);
}

export function getActivitiesByLeadId(leadId: string): ActivityWithAuthor[] {
  return MOCK_ACTIVITIES
    .filter((a) => a.lead_id === leadId)
    .sort((a, b) => new Date(b.performed_at).getTime() - new Date(a.performed_at).getTime());
}

export function getDealsByLeadId(leadId: string): DealWithLead[] {
  return MOCK_DEALS.filter((d) => d.lead_id === leadId);
}

export function getMemberName(userId: string | null): string {
  if (!userId) return "Não atribuído";
  return MOCK_MEMBERS.find((m) => m.id === userId)?.name ?? "Desconhecido";
}
